/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ui`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/index`; params?: Router.UnknownInputParams; } | { pathname: `/parent/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/tokens`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/ui`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/index`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/index`; params?: Router.UnknownOutputParams; } | { pathname: `/parent/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/theme/tokens`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/parent`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/components/ui${`?${string}` | `#${string}` | ''}` | `/auth/index${`?${string}` | `#${string}` | ''}` | `/teacher/index${`?${string}` | `#${string}` | ''}` | `/parent/index${`?${string}` | `#${string}` | ''}` | `/../src/theme/tokens${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/parent${`?${string}` | `#${string}` | ''}` | `/teacher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/ui`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/index`; params?: Router.UnknownInputParams; } | { pathname: `/parent/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/theme/tokens`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; };
    }
  }
}
