/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tenant-init`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/services/ingestion`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/routes/devices/test-push`; params?: Router.UnknownInputParams; } | { pathname: `/../../../packages/db/src/schema/audit-logs`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/services/audit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/promote`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/billing/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/bulletins`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/chat/info`; params?: Router.UnknownInputParams; } | { pathname: `/chat/walt`; params?: Router.UnknownInputParams; } | { pathname: `/classes/%5BclassId%5D/archive`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/tenant-init`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/services/ingestion`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/routes/devices/test-push`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../packages/db/src/schema/audit-logs`; params?: Router.UnknownOutputParams; } | { pathname: `/../../api/src/services/audit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/promote`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/billing/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/bulletins`; params?: Router.UnknownOutputParams; } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/info`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/walt`; params?: Router.UnknownOutputParams; } | { pathname: `/classes/%5BclassId%5D/archive`; params?: Router.UnknownOutputParams; } | { pathname: `/parent`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/tenant-init${`?${string}` | `#${string}` | ''}` | `/../../api/src/services/ingestion${`?${string}` | `#${string}` | ''}` | `/../../api/src/routes/devices/test-push${`?${string}` | `#${string}` | ''}` | `/../../../packages/db/src/schema/audit-logs${`?${string}` | `#${string}` | ''}` | `/../../api/src/services/audit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/promote${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/billing/dashboard${`?${string}` | `#${string}` | ''}` | `/bulletins${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/chat/info${`?${string}` | `#${string}` | ''}` | `/chat/walt${`?${string}` | `#${string}` | ''}` | `/classes/%5BclassId%5D/archive${`?${string}` | `#${string}` | ''}` | `/parent${`?${string}` | `#${string}` | ''}` | `/teacher${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/tenant-init`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/services/ingestion`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/routes/devices/test-push`; params?: Router.UnknownInputParams; } | { pathname: `/../../../packages/db/src/schema/audit-logs`; params?: Router.UnknownInputParams; } | { pathname: `/../../api/src/services/audit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/promote`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/billing/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/bulletins`; params?: Router.UnknownInputParams; } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/chat/info`; params?: Router.UnknownInputParams; } | { pathname: `/chat/walt`; params?: Router.UnknownInputParams; } | { pathname: `/classes/%5BclassId%5D/archive`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}` | { pathname: `/chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
    }
  }
}
